# Use an official Nginx runtime as the base image
FROM nginx:alpine

# Copy the static content to the Nginx web server root
COPY ./index.html /usr/share/nginx/html
COPY ./app.js /usr/share/nginx/html

